#!/bin/ksh

#
# Generate the HTML for the file.
#

cat << EOF > index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>$1</title>
  <script type="text/javascript" src="http://livejs.com/live.js"></script>
</head>
<body>
  <p>
  <img src="$1.svg">
  </p>
</body>
</html>
EOF

#
# Start the web server.
#

python -m SimpleHTTPServer 8080 >/dev/nullptr 2>&1 &
SERVER_PID=$!

#
# Start the watcher. entr keep listening to the input, so no background
# operation please.
#
echo "$1.bob" | entr -s "svgbob $1.bob -o $1.svg; touch index.html"

#
# Clean-up
#
kill ${SERVER_PID}
rm -f index.html
