#!/bin/ksh

#
# Check arguments
#

if [ $# -ne 6 ]
then
  echo "Usage: $0 IN.DAT TITLE [left|right] MAX_DAT MAX_XXX OUT.PDF"
  exit 0
fi

#
# Script options
#

FILE=$1
TITLE=$2
HORIZ=$3
MAX_DAT=$4
MAX_XXX=$5
OUTPUT=$6

#
# Gnuplot
#

gnuplot -persist <<-EOFMarker
  #
  # Terminal setup
  #
  # set terminal svg size 960, 540 enhanced # font "arial,10" fontscale 1.0 size 600, 400 
  # set output 'output.svg'
  # set terminal pngcairo  transparent enhanced font "arial,10" fontscale 1.0 size 600, 400 
  # set output 'output.png'
  set term pdfcairo font "Arial,16" enhanced
  set output '${OUTPUT}'
  #
  # Histogram options
  #
  set title "${TITLE}"
  set boxwidth 0.9 absolute
  set style fill solid 1.00 border lt -1
  set key fixed ${HORIZ} top vertical noreverse noenhanced autotitle nobox
  set style histogram clustered gap 1 title textcolor lt -1
  set datafile missing '-'
  set style data histograms
  #
  # X format
  #
  set xtics border in scale 0,0 nomirror rotate by -45  autojustify
  set xtics norangelimit 
  set xtics font ", 10"
  #
  # Y format
  #
  set yrange [ 0 : ${MAX_DAT} ] noreverse nowriteback
  set ytics nomirror
  set ytics font ", 10"
  set format y '%.0s%c'
  #
  # Y2 format
  #
  set y2tics nomirror
  set y2tics font ", 10"
  set y2range [ 0 : ${MAX_XXX} ] noreverse nowriteback
  #
  # Line options
  #
  set style line 1 lc rgb '#8B0000' lt 1 lw 2 pt 7 pi -1 ps .5
  set pointintervalbox 1
  #
  # Plot the histogram data
  #
  plot  '$1' using 2:xtic(1) ti col, \
        ''   using 3         ti col, \
        ''   every ::1 using (\$2/\$3) ti "Speed-up" axes x1y2 with linespoints ls 1
EOFMarker
